#!/bin/csh
#PBS -q hotel
#PBS -N naivebayes
#PBS -l nodes=1:ppn=32
#PBS -l walltime=00:10:00
#PBS -o statuses/naivebayes.out
#PBS -e statuses/naivebayes.err
#PBS -V
cd /oasis/tscc/scratch/ucsb-train22/cs240a/project/naive_bayes

echo "Trial 1" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 2" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 3" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 4" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 5" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 6" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 7" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 8" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 9" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt
echo "Trial 10" >> 20news-output.txt
./script.sh 1 2 32 >> 20news-output.txt

echo "Trial 1" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 2" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 3" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 4" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 5" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 6" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 7" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 8" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 9" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt
echo "Trial 10" >> reuters-output.txt
./script.sh 2 2 32 >> reuters-output.txt

echo "Trial 1" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 2" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 3" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 4" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 5" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 6" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 7" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 8" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 9" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt
echo "Trial 10" >> enron-output.txt
./script.sh 3 2 32 >> enron-output.txt